Ecommerce_Project/Controllers/CartController.cs
using Ecommerce_Project.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Ecommerce_Project.Controllers
{
    public class CartController : Controller
    {
        IConfiguration configuration;
        ProductCrud productCrud;
        UserCrud userCrud;
        CartCRUD cartCRUD;
        public CartController(IConfiguration configuration)
        {
            this.configuration = configuration;
            productCrud = new ProductCrud(this.configuration);
            userCrud = new UserCrud(this.configuration);
            cartCRUD=new CartCRUD(this.configuration);
        }
        // GET: CartController
        public ActionResult Index()
        {
            return View();
        }

        // GET: CartController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

     
    

        // Get: CartController/Create
        [HttpGet]
        public ActionResult AddToCart(int id)
        {
            try
            {
                Cart cart = new Cart();
                string uid = HttpContext.Session.GetString("uid");
                cart.Uid = Convert.ToInt32(uid);
                cart.Id=id;
                cart.Quantity = 1;
                int result = cartCRUD.AddTOCart(cart);
                if (result == 1)
                    return RedirectToAction(nameof(ViewCart));
                else
                    return View();
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: CartController/Edit/5

        public ActionResult ViewCart()
        {
            string uid = HttpContext.Session.GetString("uid");
            var model = cartCRUD.ViewCart(Convert.ToInt32(uid));

            return View(model);
        }

       
        // GET: CartController/Delete/5
        public ActionResult RemoveCart(int id)
        {


            try
            {
                var result = cartCRUD.DeleteCart(id);
                
                return RedirectToAction(nameof(ViewCart));
            }
            catch(Exception ex) 
            {
                return View();
            }
        }

      
    }
}

Ecommerce_Project/Controllers/CategoryController.cs
using Ecommerce_Project.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Ecommerce_Project.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IConfiguration configuration;
        private CategoryCrud crud;
        public CategoryController(IConfiguration configuration)
        {
            this.configuration = configuration;
            crud = new CategoryCrud(this.configuration);
        }
        // GET: CategoryController
        public ActionResult Index()
        {
            var model = crud.GetAllCategory();
            return View(model);
        }

        // GET: CategoryController/Details/5
        public ActionResult Details(int id)
        {
            var result = crud.GetCategoryById(id);
            return View(result);
        }

        // GET: CategoryController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CategoryController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Category category)
        {
            try
            {
                int result = crud.AddCategory(category);
                if (result == 1)
                    return RedirectToAction(nameof(Index));
                else
                    return View();
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: CategoryController/Edit/5
        public ActionResult Edit(int id)
        {
            var result = crud.GetCategoryById(id);
            return View(result);
        }

        // POST: CategoryController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Category cat)
        {
            try
            {
                int result = crud.UpdateCategory(cat);
                if (result == 1)
                    return RedirectToAction(nameof(Index));
                else return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: CategoryController/Delete/5
        public ActionResult Delete(int id)
        {
            var result = crud.GetCategoryById(id);
            return View(result);
        }

        // POST: CategoryController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult DeleteConfirm(int id)
        {
            try
            {
                int result = crud.DeleteCategory(id);
                if (result == 1)
                    return RedirectToAction(nameof(Index));
                else return View();
            }
            catch
            {
                return View();
            }
        }
    }
}

Ecommerce_Project/Controllers/OrderController.cs
using Ecommerce_Project.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Ecommerce_Project.Controllers
{
    public class OrderController : Controller
    {
        IConfiguration configuration;
        ProductCrud productCrud;
        UserCrud userCrud;
        CartCRUD cartCRUD;
        Product product;
        OrderCrud orderCrud;
        public OrderController(IConfiguration configuration)
        {
            this.configuration = configuration;
            productCrud = new ProductCrud(this.configuration);
            userCrud = new UserCrud(this.configuration);
            cartCRUD = new CartCRUD(this.configuration);
            orderCrud=new OrderCrud(this.configuration);

        }
        // GET: OrderController
        //[HttpGet]
        //public ActionResult Order()
        //{
        //    string uid = HttpContext.Session.GetString("uid");
        //    var model = cartCRUD.ViewCart(Convert.ToInt32(uid));

        //    return View(model);


        //}


        //GET: OrderController/Details/5
       
        [HttpGet]
        public ActionResult GetOrder(int id)
        {
            try
            {

                //string uid = HttpContext.Session.GetString("uid");

                var model = productCrud.GetProductById(id);

                return View(model);
            }
            catch (Exception ex)
            {
                return View();
            }
        }
        [HttpGet]
        public ActionResult GetOrderConfirm(int id)
        {
            try
            {
                Order order = new Order();
                string uid = HttpContext.Session.GetString("uid");
                order.Uid = Convert.ToInt32(uid);
                order.Id = id;
                order.Quantity = 1;
                int result = orderCrud.AddOrder(order);
                if (result == 1)
                    return RedirectToAction(nameof(MyOrder));
                else
                    return View();
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        [HttpGet]
        //[ActionName("Order")]
        public ActionResult ConfirmOrder()
        {
            return View();
        }
        // GET: OrderController/Delete/5
        public ActionResult AddToOrder(int id)
        {
            return View();
        }

        ////POST: OrderController/Delete/5
        //[HttpGet]


        public IActionResult MyOrder()
        {
            try
            {
                string uid = HttpContext.Session.GetString("uid");
                var result = orderCrud.MyOrder(Convert.ToInt32(uid));
                return View(result);
            }
            catch (Exception)
            {

                return View();
            }
           

        }
    }

}

Ecommerce_Project/Controllers/ProductController.cs
using Ecommerce_Project.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Ecommerce_Project.Controllers
{
    public class ProductController : Controller
    {
        IConfiguration configuration;
        ProductCrud productCrud;
        CategoryCrud categoryCrud;
        private Microsoft.AspNetCore.Hosting.IHostingEnvironment env;
        public ProductController(IConfiguration configuration, Microsoft.AspNetCore.Hosting.IHostingEnvironment env)
        {
            this.configuration = configuration;
            productCrud = new ProductCrud(this.configuration);
            categoryCrud = new CategoryCrud(this.configuration);
            this.env = env;
        }


        // GET: EmployeeController
        public ActionResult Index()
        {
            return View(productCrud.GetProducts());
        }


        // GET: EmployeeController/Details/5
        public ActionResult Details(int id)
        {
            return View(productCrud.GetProductById(id));
        }


        // GET: EmployeeController/Create
        public ActionResult Create()
        {
            ViewBag.Category = categoryCrud.GetAllCategory();
            return View();
        }


        // POST: EmployeeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product product, IFormFile file)
        {
            try
            {
                using (var fs = new FileStream(env.WebRootPath + "\\images\\" + file.FileName, FileMode.Create, FileAccess.Write))
                {
                    file.CopyTo(fs);
                }
                product.Imageurl = "~/images/" + file.FileName;
                var result = productCrud.AddProduct(product);
                if (result >= 1)
                    return RedirectToAction(nameof(Index));
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }
        }


        // GET: EmployeeController/Edit/5
        public ActionResult Edit(int id)
        {
            var product = productCrud.GetProductById(id);
            ViewBag.Category = categoryCrud.GetAllCategory();
            HttpContext.Session.SetString("oldImageUrl", product.Imageurl);
            return View(product);
        }


        // POST: EmployeeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product product, IFormFile file)
        {
            try
            {
                string oldimageurl = HttpContext.Session.GetString("oldImageUrl");
                if (file != null)
                {
                    using (var fs = new FileStream(env.WebRootPath + "\\images\\" + file.FileName, FileMode.Create, FileAccess.Write))
                    {
                        file.CopyTo(fs);
                    }
                    product.Imageurl = "~/images/" + file.FileName;


                    string[] str = oldimageurl.Split("/");
                    string str1 = (str[str.Length - 1]);
                    string path = env.WebRootPath + "\\images\\" + str1;
                    System.IO.File.Delete(path);
                }
                else
                {
                    product.Imageurl = oldimageurl;
                }
                var result = productCrud.UpdateProduct(product);
                if (result >= 1)
                    return RedirectToAction(nameof(Index));
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }
        }


        // GET: EmployeeController/Delete/5
        public ActionResult Delete(int id)
        {
            return View(productCrud.GetProductById(id));
        }


        // POST: EmployeeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public ActionResult DeleteConfirm(int id)
        {
            try
            {
                var product = productCrud.GetProductById(id);
                string[] str = product.Imageurl.Split("/");
                string str1 = (str[str.Length - 1]);
                string path = env.WebRootPath + "\\images\\" + str1;
                System.IO.File.Delete(path);
                var result = productCrud.DeleteProduct(id);
                if (result >= 1)
                    return RedirectToAction(nameof(Index));
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }
        }

    }
}
    

Ecommerce_Project/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Ecommerce_Project</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Ecommerce_Project.styles.css" asp-append-version="true" />
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm  border-bottom box-shadow mb-3 nav">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/brandimg.webp" height="50" width="50" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a>
                        </li>
                        @if (httpcontextAccessor.HttpContext.Session.GetString("RoleId") == "1")
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product List</a>
                        </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="UserList">User List</a>
                            </li>
                        }
                         @if (httpcontextAccessor.HttpContext.Session.GetString("RoleId") == "0")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Product List</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="MyOrder"><i class="fa fa-shopping-bag fa-2x" aria-hidden="true"></i>MyOrder</a>
                            </li>
                        }



                       
                    </ul>
                </div>
            </div>
            <ul class="navbar-nav ml-auto">
                @if (httpcontextAccessor.HttpContext.Session.GetString("RoleId") == "0")
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="ViewCart">
                            <i class="fa fa-cart-plus fa-3x" aria-hidden="true"></i>
                        </a>
                    </li>
               
                }

                @if (string.IsNullOrEmpty(httpcontextAccessor.HttpContext.Session.GetString("uid")))
                { 

                <li class="nav-item">

                    <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Registration">Register</a>
                </li>
             
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Login">Login</a>
                    </li>
                  
                }
                 @if (!string.IsNullOrEmpty(httpcontextAccessor.HttpContext.Session.GetString("uid")))
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="">Welcome @httpcontextAccessor.HttpContext.Session.GetString("userName")</a>
                    </li> 
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="LogOut">LogOut</a>
                    </li>
                }
            </ul>

        </nav>
        
        
    </header>
    <div class="container cc">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

   <footer>
        <div class="container">
@*            &copy; 2023 - Ecommerce_Project - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
*@    <div class="row">
    <div class="col-md-2">
    About
    <ul type="none">
    <li><a href="#">Contact us</a></li>
    <li><a href="#">About us</a></li>
    <li><a href="#">Careers</a></li>
    <li><a href="#">FlipKart stories</a></li>
    <li><a href="#">Press</a></li>
    <li><a href="#">FlipKart Wholesale</a></li>
    <li><a href="#">Corporate Information</a></li>

    </ul>
    </div>
    <div class="col-md-3 help">
    Help
    <ul type="none">
    <li><a href="#">Payments</a></li>
    <li><a href="#">Shipping</a></li>
    <li><a href="#">Cancellation&Return</a></li>
    <li><a href="#">FAQ</a></li>
    <li><a href="#">Report Infringement</a></li>

    </ul>
    </div>

    <div class="col-md-2">
    Consumer Policy
    <ul type="none">
    <li><a href="#">Cancellations & Returns</a></li>
    <li><a href="#">Terms of use</a></li>
    <li><a href="#">Privacy</a></li>
    <li><a href="#">Sitemap</a></li>
    <li><a href="#">Grievance Redressal</a></li>
    <li><a href="#">ERP Compliance</a></li>

    </ul>
    </div>
    <div class="col-md-1">
    Social
    <ul type="none">
    <li><a href="#">Facebook</a></li>
    <li><a href="#">Twitter</a></li>
    <li><a href="#">YouTube</a></li>

    </ul>
    </div>
    <div class="col-md-3">
    Mail Us;
    <ul type="none">
    <li>Flipkart Internet Private Limited,</li>
    <li>Building Alyssa,Begonia &</li>
    <li>Clove Embassy Tech Village,</li>
    <li>Outer Ring Road,Devarabeesanahalli Village,</li>
    <li>Bengaluru,560103,</li>
    <li>Karnataka,India</li>
    <li></li>
    </ul>
    </div>

    </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    
</body>
</html>